services:
  postgres:
    image: postgres:17-alpine
    container_name: git_town_postgres
    restart: unless-stopped
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
      - postgres_data_volume:/var/lib/postgresql/data:rw
    networks:
      - postgres_network
    ports:
      - 5432:5432
  squid:
    image: ghcr.io/b4tman/squid-ssl-bump:6.6
    container_name: git_town_squid
    restart: unless-stopped
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
      - ./squid/combined.pem:/etc/squid/combined.pem:ro
    networks:
      - squid_network
    ports:
      - 3128:3128
  fastify:
    depends_on:
      - postgres
      - squid
    image: node:22-slim
    container_name: git_town_fastify
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
        npm install --no-save &&
        npm run dev
      "
    env_file:
      - ./fastify/.env
    volumes:
      - ./fastify:/app:rw
      - fastify_node_modules:/app/node_modules:rw
    networks:
      - fastify_network
      - postgres_network
      - squid_network
    ports:
      - 8081:80
  next:
    image: node:22-slim
    container_name: git_town_next
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
        npm install --no-save &&
        npm run dev
      "
    env_file:
      - ./next/.env
    volumes:
      - ./next:/app:rw
      - next_node_modules:/app/node_modules:rw
      - next_cache:/app/.next:rw
    networks:
      - next_network
    ports:
      - 8082:80

volumes:
  postgres_data_volume:
    name: git_town_postgres_data_volume
  fastify_node_modules:
    name: git_town_fastify_node_modules
  next_node_modules:
    name: git_town_next_node_modules
  next_cache:
    name: git_town_next_cache

networks:
  postgres_network:
    driver: bridge
    name: git_town_postgres_network
  squid_network:
    driver: bridge
    name: git_town_squid_network
  fastify_network:
    driver: bridge
    name: git_town_fastify_network
  next_network:
    driver: bridge
    name: git_town_next_network
