export const API_ERRORS = {
  400: {
    default: '(400) Requête incorrecte.',
  },
  401: {
    INVALID_OAUTH_CODE: '(401) Code OAuth invalide.',
    INVALID_PASSWORD: '(401) Mot de passe invalide.',
    INVALID_SIGNATURE: '(401) Signature invalide.',
    INVALID_TEMPORARY_CODE: '(401) Code temporaire invalide.',
    INVALID_TOKEN: '(401) Jeton invalide.',
    default: '(401) Non autorisé.',
  },
  403: {
    INSUFFICIENT_PERMISSIONS: '(403) Permissions insuffisantes.',
    INSUFFICIENT_PERMISSIONS_OR_USER_ID_MISMATCH: '(403) Permissions insuffisantes ou identifiant utilisateur différent.',
    INSUFFICIENT_PERMISSIONS_OR_USER_NOT_IN_REPOSITORY: '(403) Permissions insuffisantes ou utilisateur non membre du dépôt.',
    NOT_REPOSITORY_MEMBER: '(403) Vous n\'êtes pas membre de ce dépôt.',
    SELF: '(403) Vous ne pouvez pas vous supprimer.',
    SELF_ROLE: '(403) Modification de votre propre rôle non autorisée.',
    USER_ID_MISMATCH: '(403) L\'identifiant utilisateur ne correspond pas.',
    default: '(403) Accès refusé.',
  },
  404: {
    UNKNOWN_DIPLOMA_INITIALISM: '(404) Sigle de diplôme inconnu.',
    UNKNOWN_EMAIL_ADDRESS: '(404) Adresse e-mail inconnue.',
    UNKNOWN_ENSEIGNEMENT_UNIT_ID: '(404) Unité d\'enseignement inconnue.',
    UNKNOWN_GITHUB_USER_ID: '(404) Utilisateur GitHub inconnu.',
    UNKNOWN_MILESTONE_ID: '(404) Jalon inconnu.',
    UNKNOWN_PROMOTION_ID: '(404) Promotion inconnue.',
    UNKNOWN_PROMOTION_LEVEL_INITIALISM: '(404) Niveau de promotion inconnu.',
    UNKNOWN_REPOSITORY_ID: '(404) Dépôt inconnu.',
    UNKNOWN_ROLE_KEYWORD: '(404) Rôle inconnu.',
    UNKNOWN_TARGET_PROMOTION_ID: '(404) Promotion cible inconnue.',
    UNKNOWN_TARGET_TEMPLATE_ID: '(404) Modèle cible inconnu.',
    UNKNOWN_TEMPLATE_ID: '(404) Modèle inconnu.',
    UNKNOWN_TOKEN_ID: '(404) Jeton inconnu.',
    UNKNOWN_USER_ID: '(404) Utilisateur inconnu.',
    UNKNOWN_USER_PROMOTION: '(404) Promotion de l\'utilisateur inconnue.',
    UNKNOWN_USER_REPOSITORY: '(404) Dépôt utilisateur inconnu.',
    default: '(404) Ressource non trouvée.',
  },
  409: {
    ALREADY_MEMBER: '(409) Déjà membre de l\'organisation GitHub.',
    DATE_OUT_OF_RANGE: '(409) Date hors des contraintes.',
    DUPLICATE: '(409) Configuration déjà existante.',
    DUPLICATE_EMAIL_ADDRESS: '(409) Adresse e-mail en double.',
    DUPLICATE_GITHUB_ID: '(409) Identifiant GitHub déjà utilisé.',
    DUPLICATE_INITIALISM: '(409) Sigle déjà utilisé.',
    DUPLICATE_NAME: '(409) Nom déjà utilisé.',
    DUPLICATE_TITLE: '(409) Titre déjà utilisé.',
    EMAIL_ADDRESS_DOMAIN_MISMATCH: '(409) Domaine d\'adresse e-mail non autorisé.',
    GITHUB_ID_ALREADY_DEFINED: '(409) Identifiant GitHub déjà défini.',
    HAS_NO_MILESTONES: '(409) Aucun jalon associé.',
    HAS_NO_USERS: '(409) Aucun utilisateur associé.',
    HAS_REPOSITORIES: '(409) L\'entité possède des dépôts associés.',
    HAS_TEMPLATES: '(409) L\'entité possède des modèles associés.',
    HAS_USERS: '(409) Le dépôt possède des utilisateurs associés.',
    HAS_USER_REPOSITORY: '(409) L\'utilisateur possède des dépôts associés.',
    NO_GITHUB_DATA: '(409) Aucune donnée GitHub disponible pour ce dépôt.',
    NOT_IN_REPOSITORY_PROMOTION: '(409) L\'utilisateur n\'est pas dans la promotion du dépôt.',
    OWN_ROLE: '(409) Impossible de s\'attribuer ce rôle.',
    PENDING_STATISTICS: '(409) Statistiques en cours de calcul. Réessayez plus tard.',
    SAME_DIPLOMA_INITIALISM: '(409) Même sigle de diplôme déjà utilisé.',
    SAME_EMAIL_ADDRESS: '(409) Même adresse e-mail déjà utilisée.',
    SAME_FULL_NAME: '(409) Même nom complet déjà utilisé.',
    SAME_INITIALISM: '(409) Même sigle déjà utilisé.',
    SAME_NAME: '(409) Même nom déjà utilisé.',
    SAME_PROMOTION_ID: '(409) Même promotion déjà sélectionnée.',
    SAME_PROMOTION_LEVEL_INITIALISM: '(409) Même niveau de promotion déjà utilisé.',
    SAME_REPOSITORY_ID: '(409) Même dépôt déjà sélectionné.',
    SAME_ROLE_KEYWORD: '(409) Même rôle déjà attribué.',
    SAME_TEMPLATE_ID: '(409) Même modèle déjà sélectionné.',
    SAME_TITLE: '(409) Même titre déjà utilisé.',
    SAME_USER_ID: '(409) Même utilisateur déjà présent.',
    SAME_YEAR: '(409) Même année déjà utilisée.',
    STUDENT_ROLE: '(409) Rôle étudiant non autorisé.',
    TEMPLATE_AND_MILESTONE_ID_MISMATCH: '(409) Incohérence entre modèle et jalon.',
    TARGET_HAS_MILESTONES: '(409) Le modèle cible possède des jalons.',
    TARGET_HAS_USERS: '(409) La promotion cible possède des utilisateurs.',
    TARGET_IS_OLDER: '(409) Le dépôt cible est plus ancien.',
    TARGET_IS_OLDER_THAN_1_DAY: '(409) Le dépôt cible a plus d\'un jour.',
    USER_IS_STUDENT: '(409) L\'utilisateur est étudiant.',
    YEAR_MISMATCH: '(409) Les années sélectionnées ne coïncident pas.',
    YEAR_UNEDITABLE_WHILE_LINKED_TO_REPOSITORIES: '(409) Année non modifiable car liée à des dépôts.',
    default: '(409) Conflit de requête.',
  },
  422: {
    default: '(422) Conflit entre GitHub et GitTown. Contactez l\'administrateur.',
  },
  423: {
    ARCHIVED: '(423) Dépôt archivé. Modification impossible.',
    TARGET_IS_ARCHIVED: '(423) Dépôt cible archivé.',
    default: '(423) Ressource verrouillée.',
  },
  429: {
    RATE_LIMIT_EXCEEDED: '(429) Trop de requêtes. Veuillez réessayer plus tard.',
    default: '(429) Trop de requêtes.',
  },
  500: {
    default: '(500) Erreur interne du serveur. Contactez l\'administrateur.',
  },
  504: {
    default: '(504) Délai d\'attente dépassé.',
  },
};
